Main svc
VazAnton/java-explore-with-me pull request #2
Opened 2024-06-16 15:06 UTC by VazAnton

2024-06-21 11:43 UTC, TomattmanYandex requested changes
В глаза очень бросается стилистика разбиения по пакетам
обычно выбирают что то одно, либо по фиче, либо по функционалу
а тут сразу оба, при чем в пакете моделей под каждую моель свой пакет, в пакете репозиториев все в одном пакете

Плюс дто обычно не относят к моделям, дто чаще хранят отдельно

еще есть коментарии в коде, но в основном на улучшение

2024-06-21 11:43 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/event/AdminEventController.java
> +    public List<EventFullDto> getAllEventInfoByParameters(@RequestParam(required = false) List<Long> users,
когда так много параметров
можно делать класс дто который будет содержать их всех

2024-06-21 11:43 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/model/dto/compilation/NewCompilationDto.java
> +public class NewCompilationDto {
это конечно дело вкуса и привычки, но лучше называть дтошки немного по другому, 
в начале основное имя а потом дополнительные части
и вместо слов New, для чего она
например CompilationCreationDto

2024-06-21 11:43 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/model/dto/user/NewUserRequest.java
> +    @NotBlank
@NotBlank включает в себя @NotNull

2024-06-21 11:43 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/service/user/UserServiceImpl.java
> +        if (userDtoInput.getEmail() != null) {
зачем эта проверка, ведь эта валидация есть в дто

2024-06-21 17:21 UTC, VazAnton commented on main-service/src/main/java/ru/practicum/controller/event/AdminEventController.java
> +    public List<EventFullDto> getAllEventInfoByParameters(@RequestParam(required = false) List<Long> users,
Мне пока не очень очевидно, как это сделать правильней в контроллерах. Нет случайно статьи какой-нибудь, где описывается, как такое проворачивать?

2024-06-22 18:25 UTC, TomattmanYandex commented on main-service/src/main/java/ru/practicum/controller/event/AdminEventController.java
> +    public List<EventFullDto> getAllEventInfoByParameters(@RequestParam(required = false) List<Long> users,
https://sky.pro/wiki/java/peredacha-slozhnogo-obyekta-kak-get-parametra-v-spring-mvc/
не читал, но похоже на правду

2024-06-22 18:26 UTC, TomattmanYandex approved these changes
Принято

2024-06-22 20:12 UTC, merged